### ISSUE TITLE
ValueError: Variable input_projection_wrapper/weights already existsdisallowed. Did you mean to set reuse=True in VarScope?

### ISSUE THREAD

**Issue by hoangnguyenkcv** [rayat137/Pose_3D#12]
I got this error when I run the code "create_movie.py ". Can you help me fix it? thank you!

![0000](https://user-images.githubusercontent.com/34051885/57966678-3ac8cb00-7990-11e9-8d81-89209443cf8f.jpg)

**Comment by rayat137** [comment]
Well, I didn't face any issue with the variable name within a variable scope being reused. Which version of Tensorflow are you using?

**Comment by hoangnguyenkcv** [comment]
Thank you, I change the tensorflow version to 1.10.0, and this error is fixed!
