### ISSUE TITLE
use_sh error

### ISSUE THREAD

**Issue by ilikeokoge** [rayat137/Pose_3D#5]
Hi,
I try Create a movie from a set of images and 2D predictions of README.md.
When I don't use use_sh, it looks like it is going well.
When I use use_sh, however, it doesn't work.

I think that it is caused by not finding post_accept_sh_finetuned_10it in data_util.py.
Do yo have some advise to solve this problem?

**Comment by rayat137** [comment]
Hi, 
You can download the stacked hourglass detections from this link:
https://drive.google.com/file/d/0BxWzojlLp259S2FuUXJ6aUNxZkE/view and change the filepath accordingly.

**Comment by ilikeokoge** [comment]
It work!
Thank you for advise!
