### ISSUE TITLE
how to generate preds_fed.h5

### ISSUE THREAD

**Issue by chenloveheimei** [rayat137/Pose_3D#7]
hello , my name is Long.
I want to generate the h5 file named 'preds_fed.h5'.but i don`t know how to generate it?can u tell me or share the steps?
thx,friend.

**Comment by rayat137** [comment]
Hi Long,

The preds_fed.h5 file is already provided in the directory fed. If you want to generate something similar, run stacked_hourglass on a video and save the results in h5 file.

**Comment by chenloveheimei** [comment]
OK,I had tried another way to generate the skeleton points and put them into enc_in.but thank lots for you.

**Comment by chenloveheimei** [comment]
Hello,rayat137.
if I want to use 17 2d_Pointst and generate 17 3d_Points,but the model only supports 16 2d_Points.how can i do?

**Comment by chenloveheimei** [comment]
ok,thx.

**Comment by timtensor** [comment]
Hi @chenloveheimei and @rayat137 , I am assuming that you are talking about , posenet which returns 17 keypoints. I was wondering , if you had managed to drop one of the joints and run it , I am quite curious to know your results on that,

**Comment by ShaminiKoravuna** [comment]
How can we generate the file preds_fed.h5 for our own images?
