### ISSUE TITLE
my reimplement

### ISSUE THREAD

**Issue by lck1201** [rayat137/Pose_3D#9]
Hi, I've reimplement your work here: https://github.com/lck1201/seq2seq-3Dpose, please consider adding it to your readme. Thanks！

**Comment by rayat137** [comment]
Sure. Will do so.

**Comment by rayat137** [comment]
Done it :)

**Comment by lck1201** [comment]
Thanks, but it seems like you've mis-spelled my name.. 'Chuankang', not'Chuankan', a 'g' missing..
